version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install soundfile
          command: sudo apt-get install libsndfile1
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: install pytest
          command: pip install pytest==6.2.2
      - run:
          name: tests
          command: pytest -k "not test_synthesis"
