version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: Install os libraries
          command: sudo apt-get install -y ffmpeg libsndfile1
      - restore_cache:
          key: deps-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CACHE_VERSION }}
      - run:
          name: Install dependencies
          command: sudo pip install -r requirements.txt
      - run:
          name: Install pytest
          command: sudo pip install pytest==6.2.2
      - run:
          name: Install google drive downloader
          command: sudo pip install googledrivedownloader==0.4
      - run:
          name: Install code coverage
          command: sudo pip install pytest-cov==2.12.1
      - run:
          name: Tests
          command: pytest -k "not waveglow" --cov=./
      - save_cache:
          key: deps-{{ .Environment.CACHE_VERSION }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
            - "test_samples"
      - run: 
          name: "Upload coverage to Codecov"
          uses: codecov/codecov-action@v1
          with:
            fail_ci_if_error: true
