version: 2.0
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.6
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pip install pytest==6.2.2
          name: Install pytest
      - run:
          command: pytest -k "not test_synthesis"
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
