version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install os libraries
          command: sudo apt-get install -y ffmpeg libsndfile1
      - python/load-cache
      - python/install-deps
      - run:
          name: Install pytest
          command: pip install pytest==6.2.2
      - python/save-cache
      - run:
          name: Tests
          command: pytest -k "not test_synthesis"
