version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.6
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

workflows:
  main:
    jobs:
      - build
