version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: Install os libraries
          command: sudo apt-get install -y ffmpeg libsndfile1
      - restore_cache:
          key: deps-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CACHE_VERSION }}
      - run:
          name: Install dependencies
          command: sudo pip install -r requirements.txt
      - run:
          name: Install pytest
          command: sudo pip install pytest==6.2.2
      - run:
          name: Install google drive downloader
          command: sudo pip install gdown==3.13.0
      - run:
          name: Install code coverage
          command: sudo pip install pytest-cov==2.12.1
      - run:
          name: Download resources
          command: gdown https://drive.google.com/uc?id=1CJpYcwoQ9zNA8f9gLpNxEijT9yKTqdcT && unzip test_samples.zip -d test_samples && ls test_samples/
      - save_cache:
          key: deps-{{ .Environment.CACHE_VERSION }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: Tests
          command: pytest -k "not waveglow" --cov=./

