version: 2

dependencies:
  pre:
    - sudo apt-get install -y ffmpeg libsndfile1
    - pip install -r requirements.txt
    - pip install pytest==6.2.2

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Tests
          command: pytest -k "not test_synthesis"
